field: dd9f55eb-9d1e-4e38-a030-273588c527c5 # Header Builder
fieldLayouts:
  44ff62dc-2eca-43bd-9fad-9a4d9ddd1152:
    tabs:
      -
        elements:
          -
            fieldUid: c9e8e8de-f207-4a7f-9a29-9ab1b6b63744 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f219c73b-b4de-45b5-9e80-3cbeef31f4ec # Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 37a35be0-404f-4f3d-a5d2-47a2fdbff518 # Buttons
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  37a35be0-404f-4f3d-a5d2-47a2fdbff518: # Buttons
    contentColumnType: string
    fieldGroup: null
    handle: buttons
    instructions: ''
    name: Buttons
    searchable: false
    settings:
      columns:
        __assoc__:
          -
            - 567ff355-c7cb-4367-b806-d0246a11179e # Button
            -
              __assoc__:
                -
                  - width
                  - ''
      contentTable: '{{%stc_1_buttons}}'
      fieldLayout: row
      maxRows: ''
      minRows: ''
      placeholderKey: null
      propagationMethod: all
      selectionLabel: ''
      staticField: ''
    translationKeyFormat: null
    translationMethod: site
    type: verbb\supertable\fields\SuperTableField
  c9e8e8de-f207-4a7f-9a29-9ab1b6b63744: # Heading
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Use this if you want a custom title different from the entry title. If you don''t fill in this field, the entry title will be used'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  f219c73b-b4de-45b5-9e80-3cbeef31f4ec: # Description
    contentColumnType: text
    fieldGroup: null
    handle: description
    instructions: 'Add an additional description to the page'
    name: Description
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: heroContent
name: 'Hero Content'
sortOrder: 1
