columnSuffix: null
contentColumnType: string
fieldGroup: 7e769544-ea62-49b5-84ef-77d76f60a2da # Builders
handle: headerBuilder
instructions: ''
name: 'Header Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_headerbuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
