contentColumnType: string
fieldGroup: 6fdeb603-3c3a-4fec-a819-1fcd624cb2a4 # Builders
handle: headerBuilder
instructions: ''
name: 'Header Builder'
searchable: false
settings:
  contentTable: '{{%matrixcontent_headerbuilder}}'
  maxBlocks: ''
  minBlocks: ''
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
