dateModified: 1657707173
email:
  fromEmail: brambeekman17@gmail.com
  fromName: Craftplate
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    8eaabcc4-6349-4101-b4a9-11b4a70db1f6: Craftplate
    37ef90fe-6989-4c2c-9837-2a5a6c3ba34a: Common
    66a468a2-cd23-4e16-a325-dc33bf9edffa: Craftplate
system:
  edition: solo
  live: true
  name: Craftplate
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
