enableVersioning: true
handle: homepage
name: Homepage
propagationMethod: all
siteSettings:
  3ba5f733-e6a9-442b-bb42-879ad8da0dcc: # Craftplate
    enabledByDefault: true
    hasUrls: true
    template: pages/_home
    uriFormat: __home__
type: single
